[2022-12-09T12:10:02.085+0000] {processor.py:154} INFO - Started process (PID=46) to work on /opt/airflow/dags/test2.py
[2022-12-09T12:10:02.094+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test2.py for tasks to queue
[2022-12-09T12:10:02.098+0000] {logging_mixin.py:137} INFO - [2022-12-09T12:10:02.097+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test2.py
[2022-12-09T12:10:02.132+0000] {logging_mixin.py:137} INFO - [2022-12-09T12:10:02.130+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test2.py", line 14, in <module>
    'start_date': datetime(2022, 12, 1),
TypeError: 'module' object is not callable
[2022-12-09T12:10:02.133+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test2.py
[2022-12-09T12:10:02.171+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test2.py took 0.091 seconds
[2022-12-09T12:10:32.909+0000] {processor.py:154} INFO - Started process (PID=104) to work on /opt/airflow/dags/test2.py
[2022-12-09T12:10:32.913+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test2.py for tasks to queue
[2022-12-09T12:10:32.916+0000] {logging_mixin.py:137} INFO - [2022-12-09T12:10:32.915+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test2.py
[2022-12-09T12:10:32.951+0000] {logging_mixin.py:137} INFO - [2022-12-09T12:10:32.947+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test2.py", line 14, in <module>
    'start_date': datetime(2022, 12, 1),
TypeError: 'module' object is not callable
[2022-12-09T12:10:32.953+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test2.py
[2022-12-09T12:10:33.021+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test2.py took 0.120 seconds
